spring:
  application:
    name:  "User Suport Tickets Search"
    version: "1.0.0"
  profiles:
    active: elastic
  cache:
    type: hazelcast
  codec:
    max-in-memory-size: 50MB

  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200

  elasticsearch:
    rest:
      uris: http://localhost:9200



management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    info:
      enabled: true
    health:
      show-details: always



