spring:
  application:
    name:  "User Suport Tickets Search"
    version: "1.0.0"
  profiles:
    active: reactive
  cache:
    type: hazelcast

  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200


  main:
    allow-bean-definition-overriding: true


  elasticsearch:
    rest:
      uris: http://localhost:9200



management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    info:
      enabled: true
    health:
      show-details: always



