version: '3'
services:
  elastichq:
    image: elastichq/elasticsearch-hq
    container_name: elastichq
    depends_on:
      - elasticsearch
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
      - HQ_DEBUG=False
    ports:
      - 5000:5000
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - node.master=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601


networks:
  esnet:
    driver: bridge